# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M0bKws8Fd9AHfeKwhz8J9iCpiPiF1n5m
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

df = pd.read_csv('/content/Cars Datasets 2025.csv', encoding='latin1')

"""# New Section"""

display(df.head())

display(df.info())

display(df.describe())